gunmod_SFX = {
	shoot = {
		flame = {
			start = Isaac.GetSoundIdByName("f_flame_start"),
			loop = Isaac.GetSoundIdByName("f_flame_loop"),
			finish = Isaac.GetSoundIdByName("f_flame_finish"),
		},
		minigun = {
			start = Isaac.GetSoundIdByName("f_minigun_start"),
			loop = Isaac.GetSoundIdByName("f_minigun_loop"),
			finish = Isaac.GetSoundIdByName("f_minigun_finish"),
		},
		chainsaw = {
			idlestart = Isaac.GetSoundIdByName("f_chainidle_start"),
			idleloop = Isaac.GetSoundIdByName("f_chainidle_loop"),
			idlefinish = Isaac.GetSoundIdByName("f_chainidle_finish"),
			runstart = Isaac.GetSoundIdByName("f_chainrun_start"),
			runloop = Isaac.GetSoundIdByName("f_chainrun_loop"),
			runfinish = Isaac.GetSoundIdByName("f_chainrun_finish"),
		},
		hand = {
			light = Isaac.GetSoundIdByName("f_hand_light"),
			light2 = Isaac.GetSoundIdByName("f_hand_light2"),
			light3 = Isaac.GetSoundIdByName("f_hand_light3"),
			med = Isaac.GetSoundIdByName("f_hand_med"),
			med2 = Isaac.GetSoundIdByName("f_hand_med2"),
		},
		laser = {
			light = Isaac.GetSoundIdByName("f_laser_light"),
			heavy = Isaac.GetSoundIdByName("f_laser_heavy"),
		},
		shotgun = {
			med = Isaac.GetSoundIdByName("f_shotgun_med"),
			heavy = Isaac.GetSoundIdByName("f_shotgun_heavy"),
		},
		sniper = {
			med = Isaac.GetSoundIdByName("f_sniper_med"),
			heavy = Isaac.GetSoundIdByName("f_sniper_heavy"),
		},
		rapid = {
			light = Isaac.GetSoundIdByName("f_rapid_light"),
			light2 = Isaac.GetSoundIdByName("f_rapid_light2"),
			med = Isaac.GetSoundIdByName("f_rapid_med"),
			med2 = Isaac.GetSoundIdByName("f_rapid_med2"),
			med3 = Isaac.GetSoundIdByName("f_rapid_med3"),
			heavy = Isaac.GetSoundIdByName("f_rapid_heavy"),
			silenced = Isaac.GetSoundIdByName("f_silenced_med"),
		},
		launcher = {
			light = Isaac.GetSoundIdByName("f_launcher2"),
			heavy = Isaac.GetSoundIdByName("f_launcher"),
		},
	},
	cock = {
		start = Isaac.GetSoundIdByName("r_cocka"),
		finish = Isaac.GetSoundIdByName("r_cockb"),
		start2 = Isaac.GetSoundIdByName("r_cocka2"),
		finish2 = Isaac.GetSoundIdByName("r_cockb2"),
		start3 = Isaac.GetSoundIdByName("r_cocka3"),
		finish3 = Isaac.GetSoundIdByName("r_cockb3"),
		start4 = Isaac.GetSoundIdByName("r_cocka4"),
		finish4 = Isaac.GetSoundIdByName("r_cockb4"),
		full = Isaac.GetSoundIdByName("r_fullcock"),
		full2 = Isaac.GetSoundIdByName("r_fullcock2"),
		shell = Isaac.GetSoundIdByName("r_shell"),
		shell2 = Isaac.GetSoundIdByName("r_shell2"),
	},
	grenade = {
		pinpull = Isaac.GetSoundIdByName("g_pinpull"),
		impact = Isaac.GetSoundIdByName("g_impact"),
		flameburst = Isaac.GetSoundIdByName("g_flameburst"),
		flameburst2 = Isaac.GetSoundIdByName("g_flameburst2"),
		flashbang = Isaac.GetSoundIdByName("g_flashbang"),
	},
	knife = {
		slash = Isaac.GetSoundIdByName("k_slash"),
		crit = Isaac.GetSoundIdByName("k_crit"),
		swing = {
			Isaac.GetSoundIdByName("k_swing1"),
			Isaac.GetSoundIdByName("k_swing2"),
			Isaac.GetSoundIdByName("k_swing3"),
			Isaac.GetSoundIdByName("k_swing4"),
			Isaac.GetSoundIdByName("k_swing5"),
		},
		ding = Isaac.GetSoundIdByName("k_ding"),
		deflect = Isaac.GetSoundIdByName("k_deflect"),
	},
	merch = {
		comeback = Isaac.GetSoundIdByName("m_comeback"),
		goodthings = Isaac.GetSoundIdByName("m_goodthings"),
		highprice = Isaac.GetSoundIdByName("m_highprice"),
		isthatall = Isaac.GetSoundIdByName("m_isthatall"),
		killed = Isaac.GetSoundIdByName("m_killed"),
		notenoughcash = Isaac.GetSoundIdByName("m_notenoughcash"),
		rarethings = Isaac.GetSoundIdByName("m_rarethings"),
		thankyou = Isaac.GetSoundIdByName("m_thankyou"),
		welcome = Isaac.GetSoundIdByName("m_welcome"),
		buyin = Isaac.GetSoundIdByName("m_whaddayabuyin"),
		sellin = Isaac.GetSoundIdByName("m_whaddayasellin"),
		com = {
			avidcollector = Isaac.GetSoundIdByName("m_comment_avidcollector"),
			elephant = Isaac.GetSoundIdByName("m_comment_elephant"),
			guts = Isaac.GetSoundIdByName("m_comment_guts"),
			penetrate = Isaac.GetSoundIdByName("m_comment_penetrate"),
			reloading = Isaac.GetSoundIdByName("m_comment_reloading"),
			thatsaweapon = Isaac.GetSoundIdByName("m_comment_thatsaweapon"),
			threeround = Isaac.GetSoundIdByName("m_comment_threeround"),
		},
	},
	misc = {
		attach = Isaac.GetSoundIdByName("v_attach"),
		charged = Isaac.GetSoundIdByName("v_charged"),
		click = Isaac.GetSoundIdByName("v_click"),
		empty = Isaac.GetSoundIdByName("v_empty"),
		equip = Isaac.GetSoundIdByName("v_equipment"),
		pack = Isaac.GetSoundIdByName("v_pack"),
		spin = Isaac.GetSoundIdByName("v_spin"),
		unlatch = Isaac.GetSoundIdByName("v_unlatch"),
		whoosh = Isaac.GetSoundIdByName("v_whoosh"),
		whoosh2 = Isaac.GetSoundIdByName("v_whoosh2"),
		fireburn = Isaac.GetSoundIdByName("fire_burn"),
		explosion = Isaac.GetSoundIdByName("v_explosion_small"),
		explosion2 = Isaac.GetSoundIdByName("v_explosion_small2"),
		bloodlaser = Isaac.GetSoundIdByName("v_blood_laser"),
	},
}

error()
